## Numpy- Assignment

In [1]:
# Assignment-> 1.
import numpy as np
array = np.random.randint(1,21,size = (5,5))
print("Original array:")
print(array)

# Replace all the element in the third column in 1.
array[:,2] = 1
print("Modified Array:")
print(array)

Original array:
[[ 4  8 18 19  1]
 [17  5  4  5 18]
 [19  2  9  8 16]
 [16  7  7 14 17]
 [ 4  7 13  3  9]]
Modified Array:
[[ 4  8  1 19  1]
 [17  5  1  5 18]
 [19  2  1  8 16]
 [16  7  1 14 17]
 [ 4  7  1  3  9]]


In [2]:
# 2nd
array = np.arange(1,17).reshape((4,4))
print(array)

# Replace Diagonal element with 0
np.fill_diagonal(array,0)
print("Modified array: ")
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array: 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
