# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__
np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-uz4hj350/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib direct

c:\Users\adity\Desktop\App_Development\Python\Python\NumPy\venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector= np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
#This is size of element but we want, size of memory.
# Memory size of just the array.
null_vector.size * null_vector.itemsize
# Total Memory(array setup + array)
null_vector.__sizeof__()


192

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# Through this we get the documentation of the add function in the numpy.
# Method 1st
print(np.add.__doc__)
# Method 2nd np.info
np.info(np.add)
# Methid 3rd
# !python -c "import numpy as np; np.info(np.add)"


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
nulls= np.zeros(10)
nulls[4]=1
print(nulls)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
val= np.arange(10,50)
print(val)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
# Let's try to reverse val variable.
print("Reverse a Vector: ",val[::-1])

Reverse a Vector:  [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
Three_matrix= np.arange(0,9).reshape((3,3))
print(Three_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr =np.array([1,2,0,0,4,0])
# print(np.where(arr!=0)) -----------1st Method
print(np.nonzero([arr])) # ------------2nd Method


(array([0, 0, 0]), array([0, 1, 4]))


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3)#---------1st Method
np.eye(3)#---------2nd Method

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
arr_random = np.random.random((3,3,3))
print(arr_random)

[[[0.20480405 0.33316475 0.46698615]
  [0.1141984  0.57700461 0.17942568]
  [0.92178387 0.58754825 0.6927468 ]]

 [[0.97222097 0.6422746  0.50293337]
  [0.23314439 0.29530255 0.64738107]
  [0.15684708 0.30514645 0.70286523]]

 [[0.17229315 0.65477847 0.18837374]
  [0.35080341 0.67261499 0.2357041 ]
  [0.11926069 0.98763317 0.32237837]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [39]:
arr2=np.random.randint([10,10])
print("Maximum Element: ", arr2.max())
print("Minimum Element: ",arr2.min())
# We can also used seed function which make array same every time, but if we don't used it generatr random value every time.


Maximum Element:  7
Minimum Element:  1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [12]:
import numpy as np
arr_3= np.random.random(30)
arr_3.mean()


np.float64(0.48210192818435954)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [33]:
# 1st Method
# arr_2d= np.ones((3,3))
# arr_2d[1,1]=0
# print(arr_2d)

# 2nd Method
Z= np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [50]:
arr= np.array([1,2,3])
zeros= np.zeros((3,len(arr)+2))
zeros[1,1:-1]=arr
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [53]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [10]:
import numpy as np
matrix = np.zeros((5,5))
arr = np.arange(1,5)
matrix[arr-1,arr]=arr
print(matrix)
Z = np.diag(np.arange(1,5), k=1)
print(Z)

[[0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [36]:
checkboard = np.zeros((8,8))

checkboard[::2, 1::2]=1
checkboard[1::2,::2]=1

print(checkboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [47]:
arr = np.arange(0,6*7*8).reshape((6,7,8))
print(arr)
# unravel_index=> Used to convert linear array into multiple array.
print(np.unravel_index(100,(6,7,8)))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [79]:
arr = np.array([0,1])
# Tile-> It is used to construct a new array by repeating an input.
odd_row= np.tile(arr, 4)
even_row= np.tile(arr[::-1], 4)
# Hstack-> Function used to stack arrays horizontally, meaning column-wise.
# np.tile(np.hstack((odd_row,even_row)),4).reshape((8,8))

Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [84]:
np.random.seed(42)
mat = np.random.randint(0,10,(5,5))
mat / np.linalg.matrix_norm(mat)

array([[0.21967561, 0.1098378 , 0.25628821, 0.14645041, 0.21967561],
       [0.32951341, 0.0732252 , 0.21967561, 0.25628821, 0.14645041],
       [0.1098378 , 0.25628821, 0.25628821, 0.0732252 , 0.18306301],
       [0.14645041, 0.0366126 , 0.25628821, 0.18306301, 0.0366126 ],
       [0.14645041, 0.        , 0.32951341, 0.18306301, 0.29290081]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [87]:
RGBA = np.dtype('u4')
print(RGBA)


uint32


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [91]:
a = np.ones((5,3))
b = np.ones((3,2))
# Matmul-> Used to perform matrix multiplication of two array.
c = np.matmul(a,b)
print(c)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:

arr = np.arange(11)
neg_arr = np.where((arr>=3) & (arr<=8), arr.__neg__(),arr)
print(arr)

[ 6  3 12 14 10  7 12  4  6  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [110]:
np.random.seed(42)
Z = np.random.randint(0,10,5)
print(Z)
print(f"\n1st:{Z**Z} \n2nd: { 2 << Z >> 2} \n3rd: {Z<-Z} \n4th: {Z/1/1}")

[6 3 7 4 6]

1st:[ 46656     27 823543    256  46656] 
2nd: [32  4 64  8 32] 
3rd: [False False False False False] 
4th: [6. 3. 7. 4. 6.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [112]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\adity\AppData\Local\Temp\ipykernel_9744\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\adity\AppData\Local\Temp\ipykernel_9744\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\adity\AppData\Local\Temp\ipykernel_9744\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [113]:
arr = np.random.random(5)
np.ceil(arr)

array([1., 1., 1., 1., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
import numpy as np
arr_1= np.array([1,2,3,4,5])
arr_2= np.array([5,6,7,8,9])
arr_3= np.intersect1d(arr_1,arr_2)
print(arr_3)

[5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np
#np.sqrt(-1)  # This will return nan
np.sqrt(-1)  == np.emath.sqrt(-1)  


nan


C:\Users\adity\AppData\Local\Temp\ipykernel_12932\4061090869.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)  == np.emath.sqrt(-1)
C:\Users\adity\AppData\Local\Temp\ipykernel_12932\4061090869.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))  # This will return nan


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [26]:
# from datetime import datetime,timedelta
# today = datetime.today()
# print(today)
# yesterday = today - timedelta(days=1)
# print(yesterday)
# tomorrow = today + timedelta(days=1)
# print(tomorrow)


today = np.datetime64('today')
print(today)
yesterday = today - np.timedelta64(1,'D')
print(yesterday)
tomorrow = today + np.timedelta64(1,'D')
print(tomorrow)


2025-07-16
2025-07-15
2025-07-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
import numpy as np
july2016= np.datetime64('2016-07')
np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'))


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [2]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [5]:
Z = np.random.uniform(0,10,10)
print(Z-Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))

[8. 7. 5. 1. 3. 2. 2. 9. 6. 1.]
[8. 7. 5. 1. 3. 2. 2. 9. 6. 1.]
[8. 7. 5. 1. 3. 2. 2. 9. 6. 1.]
[8 7 5 1 3 2 2 9 6 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [10]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [11]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [12]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.22989464 0.27794452 0.4708031  0.52517547 0.66614739 0.79459159
 0.8474     0.92986852 0.95385934 0.98707392]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [16]:
Z = np.arange(10)
np.add.reduce(Z)



np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.equal(A,B)
print(equal)

[1 1 0 0 1] [0 0 0 1 1]
[False False  True False  True]


#### 43. Make an array immutable (read-only) (★★☆)

In [5]:
import numpy as np
Z = np.zeros(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [6]:
Z = np.random.random((10,2))
X,Y =  Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.65155565 0.87524246 0.99066014 0.90301803 0.88011689 0.78235596
 0.98679529 0.99759152 0.86465417 1.16437473]
[0.29398522 0.66046853 0.40463747 0.42637278 0.05345633 0.27280263
 0.29423728 0.40539    0.12472018 0.75332846]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [11]:
Z = np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.81343358 0.74032943 0.29618024 0.2346185  0.13688425 0.43686928
 0.26501039 0.78795932 0.49051154 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
# meshgrid()-> It is a function that creates coordinates matrices from 1-D coordiate vectors.
# It commonl used for evaluating function on a grid, visualizing data and performing operation on M-D data.
z = np.zeros((5,5),  [('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [13]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [14]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
# Used to configure how Numpy arrays and other object are dispayed when printed.
np.set_printoptions(threshold = float('inf'))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [17]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

88


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                ('y', float, 1)]),
                ('color', [ ('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [6]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.34359204 0.61517045 0.82934948 0.34750244 0.86391714
  0.83989529 0.55132095 1.04073695 0.04782555]
 [0.34359204 0.         0.29784065 0.50132511 0.31241593 0.54289996
  0.49899576 0.21546021 0.86825877 0.29860274]
 [0.61517045 0.29784065 0.         0.21555412 0.40548611 0.2491139
  0.34337422 0.10135285 0.65240792 0.56742303]
 [0.82934948 0.50132511 0.21555412 0.         0.6080384  0.05635129
  0.27367293 0.28632347 0.64006629 0.78172448]
 [0.34750244 0.31241593 0.40548611 0.6080384  0.         0.62459937
  0.72657692 0.39945657 0.69371677 0.30971511]
 [0.86391714 0.54289996 0.2491139  0.05635129 0.62459937 0.
  0.32408594 0.33009393 0.59608623 0.81612504]
 [0.83989529 0.49899576 0.34337422 0.27367293 0.72657692 0.32408594
  0.         0.32745324 0.91185927 0.79642573]
 [0.55132095 0.21546021 0.10135285 0.28632347 0.39945657 0.33009393
  0.32745324 0.         0.74706952 0.50443853]
 [1.04073695 0.86825877 0.65240792 0.64006629 0.69371677 0.59608623
  0.91185927 0.747069

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
print(Y)
Y[:] = Z
print(Y)

[1089245163 1108593832 1110781157 1117164657 1091275478 1096432354
 1117052632 1113775119 1118893510 1115329196]
[ 7 36 45 75  8 13 74 56 88 62]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
# np.genfromtxt

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
# NULL

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
# NULL

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [75]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p),7)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 7.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [77]:
# mean(axis=,keepdims= )
# In NumPy, keepdims is a boolean parameter available in many aggregate functions like numpy.sum(), numpy.mean(), numpy.max(), etc., that operate along specified axes.


x = np.random.rand(5,10)
y = x-x.mean(axis=1, keepdims=True)
y = x-x.mean(axis=1).reshape(-1,1)
print(y)

[[-0.43884278 -0.23372055 -0.19752744  0.11471657  0.00813382 -0.0380156
   0.16219824  0.08184144  0.34641497  0.19480134]
 [ 0.32382549 -0.39568523  0.50486535  0.06172706 -0.13960659  0.27208239
  -0.26168589 -0.16157083 -0.05287077 -0.15108097]
 [ 0.33273393 -0.56301822  0.35870467  0.06187548 -0.14375325 -0.44309174
   0.27718606 -0.38182557  0.25130816  0.24988048]
 [ 0.42507025 -0.41282352  0.21503329  0.33487115 -0.35624962 -0.42069983
   0.21323461 -0.05025662  0.02755569  0.0242646 ]
 [ 0.1290954   0.15507386  0.17201016 -0.0031359  -0.17636604  0.30641022
  -0.16518892  0.2633113  -0.20803133 -0.47317874]]


#### 59. How to sort an array by the nth column? (★★☆)

In [80]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[9 7 6]
 [6 6 4]
 [1 4 1]]
[[1 4 1]
 [6 6 4]
 [9 7 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [87]:
# Null: 0
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())
# Null: 1
# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(Z)
print(np.isnan(Z).all(axis=0))

False
[[ 0.  1. nan]
 [ 1.  2. nan]
 [ 4.  5. nan]]
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [90]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

[0.20404285 0.81698169 0.83793956 0.89282603 0.65875793 0.90207408
 0.62080729 0.53622553 0.36043464 0.45639294]
0.5362255277686487


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [95]:
# numpy.nditer is an efficient, multi-dimensional iterator object in NumPy designed to traverse elements of one or more arrays in a systematic and flexible manner.
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)
it  = np.nditer([A,B,None])
for x,y,z in it: z[...] = x+y
print("Sun:\n", it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
Sun:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [96]:
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj  = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __araay_finalize__(self,obj):
        if obj is None: return
        self.name = getattr(obj,'name',"no name")

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [100]:
# numpy.bincount() is a function in the NumPy library used to count the occurrences of each non-negative integer value within a 1-dimensional array.

Z =  np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength= len(Z))
print(Z)


# Another Solution
np.add.at(Z,I,1)
print(Z)

[5. 2. 3. 3. 5. 2. 3. 4. 1. 2.]
[9. 3. 5. 5. 9. 3. 5. 7. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [101]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
#NULL

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [102]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
sum = A.sum(axis=(-2,-1))
print(sum)


[[[[7 5 5 9]
   [8 3 9 3]
   [1 2 6 1]]

  [[8 4 2 6]
   [2 5 3 7]
   [4 9 4 8]]

  [[7 1 8 7]
   [6 4 1 2]
   [3 5 1 8]]

  [[6 4 5 0]
   [4 9 2 3]
   [1 1 6 0]]]


 [[[2 9 9 0]
   [5 2 9 0]
   [2 4 3 2]]

  [[5 1 5 3]
   [8 2 4 4]
   [4 5 9 8]]

  [[0 1 0 6]
   [9 6 1 0]
   [7 7 5 1]]

  [[6 2 9 4]
   [8 6 2 6]
   [9 8 2 1]]]


 [[[6 7 7 5]
   [9 8 4 6]
   [4 6 1 6]]

  [[6 5 7 3]
   [1 1 2 1]
   [8 3 8 8]]

  [[5 6 3 5]
   [8 3 4 7]
   [4 5 8 6]]

  [[7 0 7 4]
   [0 3 5 5]
   [2 9 2 0]]]]
[[59 62 53 41]
 [47 58 43 63]
 [69 53 64 44]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
#NULL

#### 69. How to get the diagonal of a dot product? (★★★)

In [111]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

print("A: \n",A,"\nB: \n",B)

# Slow version
c = np.diag(np.dot(A,B))
print("\n DOT: ", c)

# Faster version
np.einsum("ij,ji->i", A, B)

A: 
 [[0.24907661 0.96810775 0.54140137 0.30013263 0.20160908]
 [0.46162781 0.81751669 0.41816734 0.68129083 0.5452484 ]
 [0.20972058 0.10183935 0.60618765 0.5104359  0.28534723]
 [0.64360525 0.80028173 0.04999039 0.51577701 0.06159829]
 [0.7400993  0.39449136 0.92244837 0.79027571 0.20007439]] 
B: 
 [[0.27488551 0.06690785 0.99824159 0.98425839 0.99522806]
 [0.07936094 0.51670953 0.29040984 0.39011628 0.62071721]
 [0.18118689 0.9902438  0.39550638 0.90891583 0.57762816]
 [0.58947582 0.32180763 0.83589069 0.39844159 0.47927717]
 [0.77862714 0.39528858 0.65872915 0.36125231 0.66779344]]

 DOT:  [0.57729156 1.30216785 1.0933132  1.21887339 2.0266368 ]


array([0.57729156, 1.30216785, 1.0933132 , 1.21887339, 2.0266368 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
# NULL

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [5]:
import numpy as np

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [6]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
# NULL

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
# NULL

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
# NULL

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
# NULL

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [8]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.7203796 , -0.67945886,  0.13487478, -0.66935239, -0.16952468,
       -0.27637594,  0.17883004,  0.52557981,  0.63351984, -0.08685763,
        0.77214951,  0.44563437, -0.507012  , -0.03196828, -0.80197849,
        0.0562569 ,  0.86639585,  0.02827711,  0.60189327,  0.94278822,
       -0.43976598, -0.39681509,  0.20171047, -0.82891869, -0.65547719,
        0.53474049,  0.15497129, -0.00545102, -0.92521566, -0.14566033,
       -0.93505292, -0.38137535, -0.71642334,  0.05613509,  0.59139497,
        0.20566137, -0.39480179, -0.04580183, -0.62398024,  0.88285382,
       -0.98923252,  0.86236386,  0.50444644, -0.60622994, -0.07433108,
        0.84159064, -0.29205827, -0.76930545, -0.14237755,  0.62467924,
       -0.26655717,  0.34528363, -0.97877959,  0.68070199,  0.2822527 ,
       -0.5820469 , -0.37929693, -0.67316075, -0.31700218, -0.21707218,
        0.04059948, -0.15677495,  0.23311022, -0.2879759 , -0.06841924,
        0.3677716 , -0.22390208, -0.65078115, -0.49246358, -0.94

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
# NULL

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
# NULL

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
# NULL

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
# NULL

#### 82. Compute a matrix rank (★★★)

In [ ]:
# NULL

#### 83. How to find the most frequent value in an array?

In [12]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
# NULL

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
# NULL

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
# NULL

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [16]:
import numpy as np
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0,Z.shape[0], k), axis = 0),
                    np.arange(0,Z.shape[1], k), axis = 1)
                    
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
# NULL

#### 89. How to get the n largest values of an array (★★★)

In [19]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# Slow
print(Z[np.argsort(Z)[-n:]])
# Fast
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [ ]:
# NULL

SyntaxError: invalid syntax (1782442572.py, line 14)

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
            ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                    names='col1, col2, col3',
                    formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


C:\Users\adity\AppData\Local\Temp\ipykernel_25232\3821641025.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
# NULL

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [25]:

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
# NULL

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
# NULL

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
# NULL

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
# NULL

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
# NULL

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
# NULL

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [30]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0,X.size,(N,X.size))
means = X[idx].mean(axis =1)
confint = np.percentile(means, [2.5,97.5])
print(confint)

[-0.19192361  0.21617173]
