## Numpy Array Operations

In [ ]:
import numpy as np

In [7]:
import numpy as np
arr = np.arange(1,10)
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative Indexing", arr[-2])


Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


2-D Array-> Slicing

In [24]:
import numpy as np
arr_2d = np.arange(1,10)
style = arr_2d.reshape((3,3))
print("Normal Array", style)
print("Specific Element", style[0,2])
print("Entire Row", style[1])
print("Entire Column", style[:,1])

Normal Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element 3
Entire Row [4 5 6]
Entire Column [2 5 8]


Sorting

In [37]:
unsorted= np.random.random(10)
print("Unsorted Array: ", unsorted)
print("Sorted Array: ", np.sort(unsorted),"\n") # 1st Way

# Sorting 2-D Array

arr_2d_unsorted= np.array([[3,1],[1,2],[2,3]])
print("2-D Unsorted Array: \n", arr_2d_unsorted)

print("2-D Sorted Array: \n", np.sort(arr_2d_unsorted, axis=0))

Unsorted Array:  [0.09124926 0.37262443 0.85704636 0.18643544 0.27527216 0.87679766
 0.74293569 0.18749851 0.46774262 0.66074611]
Sorted Array:  [0.09124926 0.18643544 0.18749851 0.27527216 0.37262443 0.46774262
 0.66074611 0.74293569 0.85704636 0.87679766] 

2-D Unsorted Array: 
 [[3 1]
 [1 2]
 [2 3]]
2-D Sorted Array: 
 [[1 1]
 [2 2]
 [3 3]]


Filter

In [39]:
numbers= np.arange(1,10)
even= numbers[numbers %2==0]
print(even)

[2 4 6 8]


Filter with Mask

In [44]:
mask =  numbers > 5
print("Number Greather than 5: ", numbers[mask])

Number Greather than 5:  [6 7 8 9]


Fancy Indexing vs np.where()

In [46]:
# This both are used to keep indexing of array and then we print it's value with help of numbers.
indices= [0,2,4]
print(numbers[indices])
where_result= np.where(numbers > 5)
print("Np Where: ", numbers[where_result])

[1 3 5]
Np Where:  [6 7 8 9]


Condition Array

In [50]:
condition_array=np.where(numbers>5, numbers*2, numbers)
print(condition_array)
# This is same way of using where.
#   if (numbers>5):
#       numbers*4
#   else:
#       numbers

[ 1  2  3  4  5 12 14 16 18]


Merge Array

In [54]:
arr_1= [1,2,3]
arr_2= [4,5,6]

combine= arr_1 + arr_2 # This is 1st way but sometimes it add elements.
print(combine)
concate= np.concatenate((arr_1,arr_2))
print(concate)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


Array Compatibility

In [59]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])
print("Compatibility Shape: ", a.shape == b.shape == c.shape)


Compatibility Shape:  False


Insert Row or Column

In [65]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([8,9,10])
# Adding new row in parent array
with_new_row= np.vstack((original, new_row))
print(with_new_row,"\n")

new_col = np.array([[7],[8]])
with_new_col= np.hstack((original, new_col))
print(with_new_col)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 

[[1 2 3 7]
 [4 5 6 8]]


Delete of Row & Column

In [67]:
original_2 = np.array([1,2,34,5,6])
delete= np.delete(original_2,2)
print(delete)
original_3 = np.array([[1,2,3],[4,5,6]])

[1 2 5 6]
