Creating An Array


In [1]:
import numpy as np
arr_2d= np.array([[1,2,3],[4,5,6]])
print("2-D Array: ", arr_2d)

2-D Array:  [[1 2 3]
 [4 5 6]]


Array vs List


In [10]:
py_list= [1,2,3]
print("Python list multiplication: ", py_list*2)

py_array= np.array([1,2,3]) #Element wise multiplication.
print("Python list multiplication: ", py_array*2)


Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python list multiplication:  [2 4 6]


Checking time difference between list and array


In [15]:
import time
start= time.time()
py_list= [i*2 for i in range(10000000)]
print("\n List Operation Time: ", time.time()-start)

start= time.time()
py_array= np.arange(10000000)*2
print("\n Array Operation Time: ", time.time()-start)



 List Operation Time:  1.7447571754455566

 Array Operation Time:  0.09311342239379883


Creating Array from Scretch

Zeros-> Matrix

In [3]:
import numpy as np
zeros = np.zeros((3,4))
print("Zero's Array: \n", zeros)

Zero's Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


One's-> Matrix

In [4]:
one = np.ones((2,3))
print("One's Array: \n", one)

One's Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


Constant Value Matrix

In [5]:
full = np.full((2,2),7)
print("Full Array: \n", full)

Full Array: 
 [[7 7]
 [7 7]]


Random Array


In [7]:
random = np.random.random((2,3)) # Random values always lie between 0 and 1. 
print("Random Array: \n", random)

Random Array: 
 [[0.88323426 0.06593885 0.2741716 ]
 [0.78786674 0.64024663 0.42458409]]


Sequences Array


In [8]:
seq = np.arange(0,10,2)
print("Sequence Array: \n", seq)

Sequence Array: 
 [0 2 4 6 8]


Vector & Matrix & Tensor

In [9]:
vector= np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("2-D Array: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
2-D Array: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [11]:
arr = np.array([[1,2,3,],[4,5,6]])
print("Shape", arr.shape) # It gives rows and col. number.
print("Dimension", arr.ndim) #  It gives dimensions.
print("Element Size", arr.size ) # It gives no. of element in array.
print("Data Type", arr.dtype) # It gives type of data type.

Shape (2, 3)
Dimension 2
Element Size 6
Data Type int64


Array Re-Shaping

In [ ]:
arr= np.arange(12)
print("Original Array: ", arr)
reshape= arr.reshape((4,3))# It re-shape array into as you want.
print("Re-shape", reshape)# reshape((col,rows))
flattened= reshape.flatten()# It re-shape array into one row.
print("Flattened", flattened)
revaled= reshape.ravel()# It return view instant of copy. Mean original is same.
print("Revaled", revaled)
transpose= reshape.T
print("Transpose", transpose)# Transpose meaning r->C and C->r.


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Re-shape [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened [ 0  1  2  3  4  5  6  7  8  9 10 11]
Revaled [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
